#include "Token.h"

map<TokenType, string> tokenStringMap = {
        { IDENFR,    "IDENFR" },
        { INTCON,    "INTCON" },
        { CHARCON,   "CHARCON" },
        { STRCON,    "STRCON" },
        { CONSTTK,   "CONSTTK" },
        { INTTK,     "INTTK" },
        { CHARTK,    "CHARTK" },
        { VOIDTK,    "VOIDTK" },
        { MAINTK,    "MAINTK" },
        { IFTK,      "IFTK" },
        { ELSETK,    "ELSETK" },
        { SWITCHTK,  "SWITCHTK" },
        { CASETK,    "CASETK" },
        { DEFAULTTK, "DEFAULTTK" },
        { WHILETK,   "WHILETK" },
        { FORTK,     "FORTK" },
        { SCANFTK,   "SCANFTK" },
        { PRINTFTK,  "PRINTFTK" },
        { RETURNTK,  "RETURNTK" },
        { PLUS,      "PLUS" },
        { MINU,      "MINU" },
        { MULT,      "MULT" },
        { DIV,       "DIV" },
        { LSS,       "LSS" },
        { LEQ,       "LEQ" },
        { GRE,       "GRE" },
        { GEQ,       "GEQ" },
        { EQL,       "EQL" },
        { NEQ,       "NEQ" },
        { COLON,     "COLON" },
        { ASSIGN,    "ASSIGN" },
        { SEMICN,    "SEMICN" },
        { COMMA,     "COMMA" },
        { LPARENT,   "LPARENT" },
        { RPARENT,   "RPARENT" },
        { LBRACK,    "LBRACK" },
        { RBRACK,    "RBRACK" },
        { LBRACE,    "LBRACE" },
        { RBRACE,    "RBRACE" }
};

map<string, TokenType> reserveWords = {
        { "const",   CONSTTK },
        { "int",     INTTK },
        { "char",    CHARTK },
        { "void",    VOIDTK },
        { "main",    MAINTK },
        { "if",      IFTK },
        { "else",    ELSETK },
        { "switch",  SWITCHTK },
        { "case",    CASETK },
        { "default", DEFAULTTK },
        { "while",   WHILETK },
        { "for",     FORTK },
        { "scanf",   SCANFTK },
        { "printf",  PRINTFTK },
        { "return",  RETURNTK },
//        { "do",      DOTK }
};